{% set name = "lsst-efd-client" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lsst-efd-client-{{ version }}.tar.gz
  sha256: ffb7c0bbec02e0b36e488dd4e0c695b0f3fe24c77106e688f8d2cff92c8e7af7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools-scm
    - pip ==19.2.3
    - wheel ==0.33.6
    - bump2version ==0.5.11
    - watchdog ==0.9.0
    - flake8 ==3.7.8
    - coverage ==4.5.4
    - twine
    - pytest-runner
  run:
    - python >=3.7
    - numpy <1.26
    - aioinflux
    - pandas
    - astropy
    - pyyaml
    - pytables
    - kafkit

test:
  imports:
    - lsst_efd_client

about:
  home: https://github.com/lsst-sqre/lsst-efd-client
  summary: Utility classes for working with the LSST EFD.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ktlim
