{% set name = "lsst-efd-client" %}
{% set version = "0.14.2" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lsst-ts/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0ea5b3c198d04e8b3979699721b0682aad7edb2171778b3951e0181f453eb99d

build:
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
    - wheel
    - coverage
  run:
    - python >={{ python_min }}
    - astropy-base
    - aiohttp
    - ciso8601
    - fastavro
    - kafkit
    - numpy
    - pandas
    - pyyaml
    - pytables
    - requests

test:
  imports:
    - lsst_efd_client
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/lsst-ts/lsst-efd-client
  summary: Utility classes for working with the LSST EFD.
  license: MIT
  license_file: LICENSE
  doc_url: https://lsst-efd-client.lsst.io/
  dev_url: https://github.com/lsst-ts/lsst-efd-client

extra:
  recipe-maintainers:
    - vebop
    - ktlim
